name: restaurant_local_server
description: A generic Flutter package for building local server applications with UDP discovery, HTTP REST APIs, WebSocket support, and real-time synchronization capabilities.
version: 1.0.0
repository: https://github.com/naseefcr/restaurant_billing_system
homepage: https://github.com/naseefcr/restaurant_billing_system/tree/main/restaurant_local_server
documentation: https://github.com/naseefcr/restaurant_billing_system/tree/main/restaurant_local_server#readme

environment:
  sdk: ^3.7.2
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  # Server framework
  shelf: ^1.4.0
  shelf_router: ^1.1.4
  shelf_web_socket: ^2.0.0
  shelf_cors_headers: ^0.1.5
  # Real-time communication
  web_socket_channel: ^2.4.0
  http: ^1.1.0
  # Serialization
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  # Code generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
